name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  audit-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: install deps
        run: npm ci
      - name: build site
        run: npm run build

      - name: checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./gh-pages
      - name: rsync built files
        run: |
          rsync -avz \
            --delete \
            --exclude CNAME \
            --exclude README.md \
            --exclude .git \
            --exclude .nojekyll \
            dist/ gh-pages/
      - name: commit & push built files
        run: |
          cd gh-pages
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am 'update gh-pages'
          git push
